# SPDX-License-Identifier: Apache-2.0
#
# This file is part of the M2-ISA-R project: https://github.com/tum-ei-eda/M2-ISA-R
#
# Copyright (C) 2022
# Chair of Electrical Design Automation
# Technical University of Munich

"""This module contains the python files generated by ANTLR. These are version controlled
to allow users without a working ANTLR and/or Java setup to also use M2-ISA-R.
"""

from .CLexer import CLexer as CoreDSL2Lexer
from .CListener import CListener as CoreDSL2Listener
from .CParser import CParser as CoreDSL2Parser
from .CVisitor import CVisitor as CoreDSL2Visitor
